---
- name: Overwrite Oracle the docker-compose
  hosts: oracle
  become: true
  tasks:
  - name: get statuses for docker containers
    shell: docker ps -a
    register: docker1out

  - debug: var=docker1out.stdout_lines

  - name: get status for poabridge
    shell: systemctl status poabridge
    register: serviceout

  - debug: var=serviceout.stdout_lines

  - name: stop the service
    shell: service poabridge stop

  - name: get statuses for docker containers
    shell: docker ps -a
    register: docker2out

  - debug: var=docker2out.stdout_lines

  - name: Build current oracle image
    shell: docker build -t oracle:ultimate-testing --file oracle/Dockerfile .
    delegate_to: 127.0.0.1
    become: false
    args:
      chdir: "{{ lookup('env', 'PWD') }}/.."

  - name: Replace oracle image
    replace:
      path: "/home/poadocker/bridge/oracle/{{ item }}.yml"
      regexp: 'poanetwork/tokenbridge-oracle:latest'
      replace: "oracle:ultimate-testing"
    with_items:
      - docker-compose
      - docker-compose-transfer
      - docker-compose-erc-native

  - include_tasks: oracle-add-docker-external-network.yml
    with_items:
      - docker-compose
      - docker-compose-transfer
      - docker-compose-erc-native
    loop_control:
      loop_var: file

  - name: start the service
    shell: service poabridge start

  - name: get statuses for docker containers
    shell: docker ps -a
    register: docker3out

  - debug: var=docker3out.stdout_lines
